# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dq < Formula
  desc "Query CSV, JSON, Avro, and Parquet files from the command line"
  homepage "https://github.com/razeghi71/dq"
  version "0.13.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/razeghi71/dq/releases/download/v0.13.0/dq_0.13.0_darwin_amd64.tar.gz"
      sha256 "8fb0e04a5c478485b7716e9c5d9c376266ab6584c687118fa1679c99cd760e96"

      define_method(:install) do
        bin.install "dq"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/razeghi71/dq/releases/download/v0.13.0/dq_0.13.0_darwin_arm64.tar.gz"
      sha256 "2d17b0958d93665d5ef657f7d8f5136089e717d43dc509b32392603bbda18538"

      define_method(:install) do
        bin.install "dq"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/razeghi71/dq/releases/download/v0.13.0/dq_0.13.0_linux_amd64.tar.gz"
      sha256 "629e4a887f30448799ddf0d56d09e95953f9ecfa0509d99e486c784c7581cbd9"
      define_method(:install) do
        bin.install "dq"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/razeghi71/dq/releases/download/v0.13.0/dq_0.13.0_linux_arm64.tar.gz"
      sha256 "65d78ace895bd3b1381360b15ec0c1b416103366fd393e6a07c9532a4af97813"
      define_method(:install) do
        bin.install "dq"
      end
    end
  end
end
